parameters:
    o_auth.o_auth.token_generator.class: OAuth\OAuthBundle\Services\TokenGenerator
#    o_auth_o_auth.example.class: OAuth\OAuthBundle\Example

services:
#    o_auth_o_auth.example:
#        class: %o_auth_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    o_auth.o_auth.token_generator:
        class: %o_auth.o_auth.token_generator.class%
        arguments: []