o_auth_o_auth:
    resource: "@OAuthOAuthBundle/Resources/config/routing.yml"
    prefix:   /

activity:
    resource: "@ActivityBundle/Resources/config/routing.yml"
    prefix:   /

ClientBundle:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /