client_homepage:
    pattern:  /
    defaults: { _controller: ClientBundle:Default:index }

client_login:
    pattern: /account/login
    defaults: { _controller: ClientBundle:Account:login }

client_logout:
    pattern: /account/logout
    defaults: { _controller: ClientBundle:Account:logout }

client_create_account:
    pattern: /account/create
    defaults: { _controller: ClientBundle:Account:create }