parameters:
#    client.example.class: Prodtrack\ClientBundle\Example

services:
#    client.example:
#        class: %client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
