parameters:
#    activity.example.class: Prodtrack\Bundle\Example

services:
#    activity.example:
#        class: %activity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
