parameters:
    prodtrack.user_service.class: Prodtrack\Bundle\Services\UserService

services:
    prodtrack.user_service:
        class: %prodtrack.user_service.class%
        arguments:
          entityManager: "@doctrine.orm.entity_manager"